# Generated by Django 2.2 on 2022-12-08 12:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeresCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='Серия карты')),
            ],
            options={
                'verbose_name': 'Серия карты',
                'verbose_name_plural': 'Серии Карт',
            },
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Формат номера карты: 1234-1234-1234-1234', regex='^([0-9]{4}[-]){3}[0-9]{4}$')], verbose_name='Номер карты')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('use_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата использования')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('status', models.CharField(choices=[('active', 'Активирована'), ('not_active', 'Не активирована'), ('overdue', 'Просрочена')], default='not_active', max_length=255, verbose_name='Статус')),
                ('series', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='main.SeresCard', verbose_name='Серия карты')),
            ],
            options={
                'verbose_name': 'Платежная карта',
                'verbose_name_plural': 'Платежные карты',
            },
        ),
        migrations.CreateModel(
            name='HistoryTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Дата транзакции')),
                ('type', models.CharField(choices=[('received_account', 'Поступило на счет'), ('debited_account', 'Списано со счета')], max_length=255, verbose_name='Тип транзакции')),
                ('sum', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сумма')),
                ('payment_card', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, related_name='history_transactions', to='main.PaymentCard', verbose_name='Платежная карта')),
            ],
            options={
                'verbose_name': 'История транзакции',
                'verbose_name_plural': 'История транзакций',
            },
        ),
    ]
